### ISSUE TITLE
Component can't connect to magicswitchbot

### ISSUE THREAD

**Issue by chronoszgz** [ec-blaster/magicswitchbot-homeassistant#2]
Hi ec-blaster,

 i have a simple configuration yaml, with no password and hci0 running.
BLE as device tracker detect the device:
root@aml:~# hcitool lescan
LE Scan ...
34:14:B5:4A:37:2F (unknown)
34:14:B5:4A:37:2F MagicSwitchBot

Also, I have tracked this device with ble in ha:
![image](https://user-images.githubusercontent.com/60244007/112228776-1e53e480-8c32-11eb-946e-3f956663f4c5.png)

But component can't connect. This is the debug logguer:

Logger: custom_components.switch
Source: custom_components/magicswitchbot/switch.py:149
Integration: Interruptor (documentation)
First occurred: 23:24:17 (2 occurrences)
Last logged: 23:24:20

Error adding entities for domain switch with platform magicswitchbot
Error while setting up magicswitchbot platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 317, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 509, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 529, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/magicswitchbot/switch.py", line 101, in async_added_to_hass
    await self._hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/magicswitchbot/switch.py", line 149, in update
    self._battery_level = self._device.get_battery()
  File "/usr/local/lib/python3.8/site-packages/magicswitchbot/__init__.py", line 628, in get_battery
    ok = self._sendCommand(self.CMD_GETBAT, "01", self._retry_count)
  File "/usr/local/lib/python3.8/site-packages/magicswitchbot/__init__.py", line 438, in _sendCommand
    self._connect()
  File "/usr/local/lib/python3.8/site-packages/magicswitchbot/__init__.py", line 236, in _connect
    self._device = PeripheralExt(deviceAddr=self._mac,
  File "/usr/local/lib/python3.8/site-packages/magicswitchbot/__init__.py", line 37, in __init__
    self._connect(deviceAddr, addrType, iface, timeout)
  File "/usr/local/lib/python3.8/site-packages/magicswitchbot/__init__.py", line 56, in _connect
    while rsp['state'][0] == 'tryconn':
TypeError: 'NoneType' object is not subscriptable

Also, these generic error witch BLE:
Logger: pygatt.backends.gatttool.gatttool
Source: /usr/local/lib/python3.8/site-packages/pygatt/backends/gatttool/gatttool.py:352
First occurred: 23:25:13 (110 occurrences)
Last logged: 23:48:20

Unexpected error when scanning: Set scan parameters failed: I/O error

Logger: custom_components.bluetooth_le_tracker.device_tracker
Source: custom_components/bluetooth_le_tracker/device_tracker.py:114
Integration: bluetooth_le_tracker (documentation)
First occurred: 23:25:13 (110 occurrences)
Last logged: 23:48:20

Error during Bluetooth LE scan: Unexpected error when scanning: Set scan parameters failed: I/O error

any suggest?
Maybe the bluetooth adapter is not working properly.

Thanks in advance!

**Comment by ec-blaster** [comment]
Hi @chronoszgz .

Several things to consider:

* How are you running HA? Is it HASSIO? HA Core? Are you using a Python VirtualEnv?
* If you are running HA Core, are you running it with a non-root account?
* And if you are running with a non-root account, did you allow it to [access the bluetooth hardware](https://github.com/ec-blaster/magicswitchbot-homeassistant#special-requirements)?

And then some other things:
* It seems to me that you have a conflict with 2 different libraries trying to access the bluetooth hardware.
* You have errors relative to `pygatt`, and the library my component uses is `bluepy`.

If you are running HA Core, could you please test the library is working using [this example](https://github.com/ec-blaster/pyMagicSwitchbot/blob/main/test.py)

Keep me informed, thanks.

**Comment by chronoszgz** [comment]
I am running HA with this:
Core
Versión
core-2021.3.4

Supervisor
Versión
supervisor-2021.03.6
Canal stable

Sistema operativo
Debian GNU/Linux 10 (buster)
Versión de Docker
19.03.13

With root account . I can access to the bluetooth hardware with hcitool or bluetoothctl and I can scan and discover BT devices and BTLE devices. MagicSwitchBot one of them.

I don't know how run the test.py in HA Core. Python is installed in host machine not in docker container with HA. If I execute python3 test.py (with the MAC of my magicswitchbot) the result is:
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    from magicswitchbot import MagicSwitchbot
ModuleNotFoundError: No module named 'magicswitchbot'

Regards!

**Comment by chronoszgz** [comment]
Ey! Good news, the F*** app did not clear the password... Now the test.py is wprking. Restarting HA

**Comment by chronoszgz** [comment]
It works!!!! Thanks EC-BLASTER!!
I needed to install:
apt install python3-setuptools  (which it's necessary for the next step)
pip3 install pyMagicSwitchbot instead of "pip install magicswithbot"

and then restart Home Assistant.

Very good job ec-blaster!

**Comment by ec-blaster** [comment]
Congratulations!
