### ISSUE TITLE
It is not possible to manage one magic switchbot from two home assistant servers

### ISSUE THREAD

**Issue by trx900** [ec-blaster/magicswitchbot-homeassistant#3]
Hi @ec-blaster, thank you so much for this great plugin, a much needed component for many smart home enthusiasts! I tested the functionality and drew attention to some usage restrictions. If you install the component on two home assistant servers on the same network, it is impossible to manage the same magic switch bot. Also, if you use the original application in parallel with the integration in the home assistant, then also control from the application becomes impossible. I specifically tested the model when I removed the home assistant integration, then installed the app on two phones, while everything was perfectly controlled from both gadgets in parallel. If this is true, then I would like to remove the restriction and manage magic switch boot from different home assistant servers on the same network. Thanks!

**Comment by ec-blaster** [comment]
Next release will allow to share the devices both between HA instances and the original App.

I'm testing it (connection-fixing branch ) and will merge it into main soon

**Comment by trx900** [comment]
OK, thanks. Will wait.

**Comment by ec-blaster** [comment]
Please check the v0.0.3 release.

I hope it solves some of your connection problems...

**Comment by ec-blaster** [comment]
Closed due to inactivity
