### ISSUE TITLE
XU4 Device ID

### ISSUE THREAD

**Issue by johnjoemorgan** [ec-blaster/magicswitchbot-homeassistant#5]
Advice please:

Using Odroid XU4 with Supervisor.

The BT dongle shows in supervisor under 3-1.2

/dev/bus/usb/003/005

With attributes:

BUSNUM: '003'
DEVNAME: /dev/bus/usb/003/005
DEVNUM: '005'
DEVPATH: /devices/platform/soc/soc:usb3-0/12000000.dwc3/xhci-hcd.8.auto/usb3/3-1/3-1.2
DEVTYPE: usb_device
DRIVER: usb
ID_BUS: usb
ID_MODEL: BT_DONGLE10
ID_MODEL_ENC: BT\x20DONGLE10
ID_MODEL_ID: '0001'
ID_PATH: platform-xhci-hcd.8.auto-usb-0:1.2
ID_PATH_TAG: platform-xhci-hcd_8_auto-usb-0_1_2
ID_REVISION: '8891'
ID_SERIAL: 0a12_BT_DONGLE10
ID_USB_INTERFACES: ':e00101:'
ID_VENDOR: 0a12
ID_VENDOR_ENC: 0a12
ID_VENDOR_ID: 0a12
MAJOR: '189'
MINOR: '260'
PRODUCT: a12/1/8891
SUBSYSTEM: usb
TYPE: 224/1/1
USEC_INITIALIZED: '682612693578'

What device ID would I need to use?  I have tried nothing, 0, 1 and 5

Error:

Logger: magicswitchbot
Source: /usr/local/lib/python3.8/site-packages/magicswitchbot/__init__.py:295
First occurred: 21:34:48 (3 occurrences)
Last logged: 21:34:51

MagicSwitchbot[FC:45:C3:CB:60:1C] Couldn't connect to device (Failed to connect to peripheral FC:45:C3:CB:60:1C, addr type: public)

**Comment by johnjoemorgan** [comment]
Changed the BLE dongle to new device:

BUSNUM: '003'
DEVNAME: /dev/bus/usb/003/062
DEVNUM: '062'
DEVPATH: /devices/platform/soc/soc:usb3-0/12000000.dwc3/xhci-hcd.8.auto/usb3/3-1/3-1.2
DEVTYPE: usb_device
DRIVER: usb
ID_BUS: usb
ID_MODEL: CSR8510_A10
ID_MODEL_ENC: CSR8510\x20A10
ID_MODEL_ID: '0001'
ID_PATH: platform-xhci-hcd.8.auto-usb-0:1.2
ID_PATH_TAG: platform-xhci-hcd_8_auto-usb-0_1_2
ID_REVISION: '2520'
ID_SERIAL: 0a12_CSR8510_A10
ID_USB_INTERFACES: ':e00101:'
ID_VENDOR: 0a12
ID_VENDOR_ENC: 0a12
ID_VENDOR_ID: 0a12
MAJOR: '189'
MINOR: '317'
PRODUCT: a12/1/2520
SUBSYSTEM: usb
TYPE: 224/1/1
USEC_INITIALIZED: '859912840902'

Everything working well.  MY thought is that the original BLE dongle was not Linux compatible.

**Comment by ec-blaster** [comment]
Perfect, thanks for the feedback
