### ISSUE TITLE
Switch long press.

### ISSUE THREAD

**Issue by Cirion75** [ec-blaster/magicswitchbot-homeassistant#6]
I'm using my MagicSwitchbot to reset a burner.

Press and hold longer than 1 second but less than 3, resets the burner.
Press and hold longer than 3 seconds, shows error code.
Presses shorter than 1 second, does nothing.

Is there a way to make the button press last for 1-3 seconds?

**Comment by ec-blaster** [comment]
No, sorry.

As far as I know, the firmware of the device does not allow you to choose the timing of the "press" command, it only allows you to issue the command and that's all.

For that you should change the firmware itself, and I don't think that's possible for us.
