### ISSUE TITLE
New update ( 2022.4.4) seems to have broken the integration

### ISSUE THREAD

**Issue by mindogo1** [ec-blaster/magicswitchbot-homeassistant#8]
Integration no longer works after the update.

Logger: magicswitchbot
Source: /usr/local/lib/python3.9/site-packages/magicswitchbot/__init__.py:295
First occurred: 12:21:35 PM (6 occurrences)
Last logged: 12:21:39 PM

MagicSwitchbot[34:14:B5:4A:9C:9F] Couldn't connect to device (Failed to connect to peripheral 34:14:B5:4A:9C:9F, addr type: public)

**Comment by ec-blaster** [comment]
Hi.
Sorry for the delay, but I was waiting to have time and check it for myself.
I've just upgraded my setup to 2022.5.2 and the component still works flawlessly.
Must be some other problem, not related to version.
