### ISSUE TITLE
Doesn't work with home assistant v2022.7.0

### ISSUE THREAD

**Issue by mnowok** [ec-blaster/magicswitchbot-homeassistant#9]
Seems like HA python 3.10 update with missing bluepy and pybluez libraries casues magicswitchbot to stop working.

**Comment by janfajessen** [comment]
I corroborate it, it's true. Since 2022.7 don't work. Hope you can fix it when you can

**Comment by Zylazy** [comment]
The same issue at me. :(

**Comment by vladeha** [comment]
The same issue

**Comment by ec-blaster** [comment]
Hi.

Sorry for the late reply. When I read the HA 2022.7 changelog, I knew I had to recode the library. I'll do as soon as I can. I'm on vacation right now and haven't had the time to update my installation

**Comment by Zylazy** [comment]
Thank you very much in advance. We all really appreciate your effort.

**Comment by chronoszgz** [comment]
Thanks EC!! Relax and enjoy your holidays!! Regards!!

**Comment by mindogo1** [comment]
Is there any update on this?

**Comment by szymonkonopek** [comment]
2022.8.7 also doesn't work :/

**Comment by vladeha** [comment]
> 2022.8.7 also doesn't work :/

It won't work more without re-writing code ! Root cause - missing bluepy and pybluez libraries .

**Comment by ec-blaster** [comment]
Sorry, I have not much time to code. I'm working at it but slowly.
The library is working already (test branch), and the component has some problems yet.
I'll do my best to have it working in about 15 days!

**Comment by Zylazy** [comment]
Thank you very much for the update! I appreciate it very much.

ec-blaster ***@***.***> ezt írta (időpont: 2022. szept. 23.,
P 18:44):

**Comment by vladeha** [comment]
> Sorry, I have not much time to code. I'm working at it but slowly. The library is working already (test branch), and the component has some problems yet. I'll do my best to have it working in about 15 days!

thank you)

**Comment by 00punisher** [comment]
> Sorry, I have not much time to code. I'm working at it but slowly. The library is working already (test branch), and the component has some problems yet. I'll do my best to have it working in about 15 days!

Thank you!! Highly appreciated!!

**Comment by ec-blaster** [comment]
Hi there.

I've just pre-released the v1.1.0 version of the component.

You can test it in HACS if you configure the repository for beta versions.

**Comment by janfajessen** [comment]
I have already updated to this  beta version but don't work in my RPi4, but this also happens with a Switchbot bot integration, I need to reload the bluetooth manually via UI sometimes more than one time to work. 

I try to reload bluetooth integration but never work...
This is the log error:
``
Logger: homeassistant.config_entries
Source: custom_components/magicswitchbot/coordinator.py:34
Integration: Dispositivo MagicSwitchbot (documentation, issues)
First occurred: 23:41:13 (1 occurrences)
Last logged: 23:41:13

Error setting up entry MagicSwitchbot for magicswitchbot
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/magicswitchbot/__init__.py", line 83, in async_setup_entry
    coordinator = hass.data[DOMAIN][entry.entry_id] = MagicSwitchbotDataUpdateCoordinator(
  File "/config/custom_components/magicswitchbot/coordinator.py", line 34, in __init__
    super().__init__(hass, logger, ble_device.address)
TypeError: PassiveBluetoothDataUpdateCoordinator.__init__() missing 1 required positional argument: 'mode'
``
Although it doesn't work, thanks for your work.

**Comment by chronoszgz** [comment]
Thanks EC-Blaster! I have exactly the same error too... maybe we are doing something wrong...

**Comment by ec-blaster** [comment]
Hi.

Today I published a new release that solves that error. There was a change in the bluetooth library in 2022.9.1.
If you update HA to 2022.10 and my integration to v1.1.1, it should work.

Mine does, and was getting the same error.

Try it.

**Comment by mnowok** [comment]
Tested with two switches, both of them haven't been used for a while so they were discharged. As soon I connected them to the charger both of them have been detected by HA automatically. Everything works fine. I'm using esphome ESP32 BLE proxy introduced a month ago. Version 2022.10 added active BLE support. I disabled raspberry bluetooth and using ESP32 proxy i was able to control magicbot switches. Very good job 👍👏. Thanks for this update. If nobody has issues with this version I think we can close this issue.

**Comment by vladeha** [comment]
Both my magicswitchbotes have been detected by HA (Bluetooth integration)  automatically after charging ! Now it works without issues ) Version 2022.9.7 Thank you!

**Comment by janfajessen** [comment]
Yes! It woks with my RPi4 Bluetooth integration! Must disable the Passive Bluetooth hacs integration also for Switchbot bot works.

Thank you for your work

**Comment by ec-blaster** [comment]
> Tested with two switches, both of them haven't been used for a while so they were discharged. As soon I connected them to the charger both of them have been detected by HA automatically. Everything works fine. I'm using esphome ESP32 BLE proxy introduced a month ago. Version 2022.10 added active BLE support. I disabled raspberry bluetooth and using ESP32 proxy i was able to control magicbot switches. Very good job 👍👏. Thanks for this update. If nobody has issues with this version I think we can close this issue.

Nice to know.
That was going to be my next tests. I have a Bluetooth dongle attached with a long cable to get it as near as possible to my magicswitchbots, but I have several Esp32 with ESPHOME and wanted to try the new Bluetooth proxy feature. Thanks for testing.

**Comment by Zylazy** [comment]
I had no time to test it earlier, and now I can see it works for "everyone", but I am not so lucky.
I am running my HA on a RP4 without dongle (only with the inbuild BT of RP), with the latest versions HA 2022.10.5 and Core system 9.2
The "bluetooth:" line is added to my configuartion.yaml
When I try to add MagicSwitch integration after a HA restart, then it shows a couple of mac addresses, but non of them can be installed successfully. Even if it isntalled then is shows the following error message:
Retrying setup: Could not find MagicSwitchbot with address XX:XX:XX:XX:XX:XX
And a couple of minutes/seconds later no mac address is displayed (even if I delete the previous intsllations), and I get always the following message: No unconfigured devices found.
Can you please help me with this issue? What did I wrong?

**Comment by ec-blaster** [comment]
MagicSwitchbot devices are not very good when we talk about Bluetooth signal power.

Try to get the devices closer to your dongle or use a larger cable, or maybe ESPHOME Bluetooth proxy...
